trigger:
  - milton-development  # Asume que deseas desencadenar la pipeline en commits a la rama 'main'

pool:
  name: LifeJourney

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.7.0'  # Asegúrate de usar la versión de Node.js que coincida con tu proyecto
    displayName: 'Instalar Node.js'

  - script: |
      npm install
      npm test
    displayName: 'Instalar dependencias y ejecutar pruebas'
