# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

resources:
  - repo: self

pool:
  name: LifeJourney

steps:
  - script: |
      docker build -t milbtonb18/lifejourney:1.0 .
    displayName: 'Construir imagen Docker'
