trigger:
  - main

resources:
  - repo: self

pool:
  name: LifeJourney

steps:
  - script: |
      docker build -t milbtonb18/lifejourney:1.0 .
    displayName: 'Construir imagen Docker'

  - script: |
      docker run -d --name lifejourney-container -p 8090:80 milbtonb18/lifejourney:1.0
    displayName: 'Ejecutar contenedor Docker'
